title: "Prosjektportalen brukermanual"
remote_theme: pmarsceill/just-the-docs
search_enabled: true
# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/
# Aux links for the upper right navigation
 aux_links:
  "Prosjektportalen 365 på GitHub":
    - "//github.com/Puzzlepart/prosjektportalen365"